# Generated by Django 6.0.5 on 2026-05-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandscapeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('landscape_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radionuclides.landscapetype')),
            ],
        ),
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1999, '1999'), (2009, '2009'), (2023, '2023')])),
                ('depth_cm', models.FloatField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radionuclides.samplinglocation')),
            ],
        ),
        migrations.CreateModel(
            name='RadionuclideMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radionuclide', models.CharField(choices=[('Cs137', 'Cs-137'), ('Sr90', 'Sr-90'), ('Pu238', 'Pu-238'), ('Pu239_240', 'Pu-239+240'), ('Am241', 'Am-241')], max_length=20)),
                ('concentration', models.FloatField(help_text='Бк/кг')),
                ('uncertainty', models.FloatField(blank=True, help_text='±', null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='radionuclides.soilsample')),
            ],
        ),
    ]
